version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install aws cli
          command: |
            apk add --no-cache aws-cli==1.22.26

      - run:
          name: Build Docker image
          command: |
            cd yelb-db/
            docker build -t yeldb .

      - run:
          name: Config AWS
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-west-1



      - run:
          name: Pushing to ECR
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              login="$(aws ecr get-login --region us-west-1)"
              ${login}
              docker tag yelbdb "${ECR_ENDPOINT}/yelbdb:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/yelbdb:${CIRCLE_SHA1}"
            fi
