version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10-git
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_REGION
    steps:
      - checkout
      - run:
          name: Install aws cli
          command: |
            apk add --no-cache aws-cli

      - run:
          name: Build Docker image
          command: |
            cd yelb-db/
            docker build -t yeldb .
            $(aws ecr get-login --no-include-email)
            docker tag yelbdb:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yelbdb:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yelbdb:latest
