version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10-cli
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install aws cli
          command: |
            apk add --no-cache aws-cli

      - run:
          name: Build Docker image
          command: |
            cd yelb-db/
            docker build -t yeldb .

      - run:
          name: Pushing to ECR
          command: |
            $(aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 237889007525.dkr.ecr.us-west-1.amazonaws.com)
            docker tag yelbdb:latest $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/yelbdb:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/yelbdb:latest
