version: 2.1

jobs:
  build:
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_REGION
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
              apk update
              apk add --no-cache ca-certificates curl gnupg
              curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | gpg --import
              echo "https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/stable" >> /etc/apk/repositories
              apk update
              apk add docker

      - run:
          name: Build Docker image
          command: |
            cd yelb-db/
            docker build -t yeldb .
            $(aws ecr get-login --no-include-email)
            docker tag yelbdb:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yelbdb:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yelbdb:latest
